### ISSUE TITLE
Error in latest version of Julia - julia 1.6.3

### ISSUE THREAD

**Issue by celavek** [Otepipi/DesignStructureMatrix.jl#9]
I get an error trying to run the simple example with the latest Julia version. I'm on  Linux. 
I would appreciate any help as this is my first encounter with Julia and I would like to use your package for a DSM training.
I looked in the source code and there is no variable with that name, so I'm a bit confused.

```
julia> plotDSM(A,label)
ERROR: UndefVarError: nokonoko1 not defined
Stacktrace:
 [1] plotDSM(DSM::Matrix{Int64}, label::Vector{String})
   @ DesignStructureMatrix ~/.julia/packages/DesignStructureMatrix/kXTgk/src/DesignStructureMatrix.jl:16
 [2] top-level scope
```

**Comment by Otepipi** [comment]
@celavek  I'm sorry. I fixed it in version 0.20, which I just released.
